### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by ANdR3Wss** [skyiea314/auto_joinDaoMeng#3]
您好！请问我登录不了是怎么回事，账号密码都输对了，但他提示“请检查账号密码”

**Comment by Dragon1573** [comment]
@ANdR3Wss 我连这个提示都没有，直接就出现`Exception`了……

**********

# 问题反馈

脚本无法完成登录过程。

# 复现步骤

1. 准备 Python v3.7.9 解释器，
2. 将项目克隆至本地，并使用 PyCharm 打开项目目录，
3. 借助 Virtualenv 创建项目级虚拟环境，激活后使用`pip install -r requirements.txt`安装依赖项，
4. 配置 PyCharm 启动脚本`auto_join.py`

# 错误日志

```text
请输入账号1*********6
请输入密码s************x
Traceback (most recent call last):
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python-379\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "D:\Python-379\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "D:\Python-379\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='appdmkj.5idream.net', port=443): Max retries exceeded with url: /v2/login/phone (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Projects/Daomeng-Auto-Join/auto_join.py", line 148, in <module>
    main()
  File "D:/Projects/Daomeng-Auto-Join/auto_join.py", line 134, in main
    if opreation.login():
  File "D:/Projects/Daomeng-Auto-Join/auto_join.py", line 41, in login
    if get_token(acc, pwd):
  File "D:\Projects\Daomeng-Auto-Join\jiami.py", line 103, in get_token
    if login.get_token_pho(acc, pwd):
  File "D:\Projects\Daomeng-Auto-Join\jiami.py", line 90, in get_token_pho
    res = requests.post(url, headers=self.headers, data=data).json()
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Projects\Daomeng-Auto-Join\venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='appdmkj.5idream.net', port=443): Max retries exceeded with url: /v2/login/phone (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

Process finished with exit code 1
```
